name: adotai
description: Aplicativo que facilita a adoção de animais.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.13.7
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  flushbar: ^1.10.4
  get_it: ^4.0.2
  http: ^0.12.1
  dynamic_theme: ^1.0.1
  maps_launcher: ^1.2.0
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.5

flutter:

  uses-material-design: true
  assets:
    - lib/assets/

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/icon_complete.png"
  image_path_android: "lib/assets/icon_complete.png"
  adaptive_icon_background: "lib/assets/icon_background.png"
  adaptive_icon_foreground: "lib/assets/icon_foreground.png"